/**
 * Tests for the mobile bridge (mobile-bridge.cjs + mobile-link-crypto.cjs +
 * mobile-link-store.cjs).
 *
 * Run with: node --test electron/mobile-bridge.test.cjs
 *
 * Why this matters: the bridge is the security boundary between the internet
 * (via the relay) and the local Jarvis brain. Pairing must be one-shot and
 * expiring, device tokens must gate every session, revocation must
 * disconnect immediately, the envelope layer must reject tampering and
 * replays, and the RPC/HTTP allowlists must refuse everything not explicitly
 * meant for phones — before it reaches the dashboard.
 *
 * The "phone" in these tests uses the same crypto module the bridge does;
 * true cross-implementation vectors for the Swift app live in the iOS repo's
 * fixtures (generated by generateTestVectors()).
 */

const assert = require('node:assert/strict')
const fs = require('node:fs')
const http = require('node:http')
const os = require('node:os')
const path = require('node:path')
const { EventEmitter } = require('node:events')
const { test } = require('node:test')
const WebSocket = require('ws')
const { WebSocketServer } = require('ws')

const {
  buildPairingUrl,
  fromB64url,
  generateLinkKey,
  generateTestVectors,
  openEnvelope,
  parsePairingUrl,
  sealEnvelope
} = require('./mobile-link-crypto.cjs')
const { createMobileLinkStore } = require('./mobile-link-store.cjs')
const {
  collectLanUrls,
  createMobileBridge,
  isRpcAllowedFromMobile,
  relayDeviceEndpoint,
  relayHostEndpoint
} = require('./mobile-bridge.cjs')

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'jarvis-mobile-test-'))
}

// ── Fake upstream dashboard socket ─────────────────────────────────────

const fakeUpstreams = []

function FakeUpstream(url) {
  const upstream = new EventEmitter()

  upstream.url = url
  upstream.readyState = 1
  upstream.sent = []
  upstream.send = text => upstream.sent.push(String(text))
  upstream.close = () => {
    upstream.readyState = 3
    upstream.emit('close')
  }

  fakeUpstreams.push(upstream)
  setImmediate(() => upstream.emit('open'))

  return upstream
}

/** Routes dashboard sockets to fakes; anything else dials out for real. */
function WebSocketRouter(url, options) {
  if (String(url).includes('/api/ws')) {
    return FakeUpstream(url)
  }

  return new WebSocket(url, options)
}

// ── Fake phone speaking the envelope protocol over a real socket ───────

class FakePhone {
  constructor(wsUrl, { key, keyId }) {
    this.key = key
    this.keyId = keyId
    this.seqOut = 0
    this.queue = []
    this.waiters = []
    this.closed = false
    this.ws = new WebSocket(wsUrl)
    this.ws.on('message', data => {
      const frame = openEnvelope(this.key, String(data))
      const waiter = this.waiters.shift()

      if (waiter) waiter(frame)
      else this.queue.push(frame)
    })
    this.ws.on('close', () => {
      this.closed = true

      for (const waiter of this.waiters.splice(0)) {
        waiter(null)
      }
    })
  }

  async open() {
    await new Promise((resolve, reject) => {
      this.ws.once('open', resolve)
      this.ws.once('error', reject)
    })

    return this
  }

  send(type, body, { keyId = this.keyId, rawSeq = null } = {}) {
    this.seqOut = rawSeq ?? this.seqOut + 1
    this.ws.send(sealEnvelope(this.key, keyId, this.seqOut, type, body))
  }

  sendRaw(text) {
    this.ws.send(text)
  }

  async next(timeoutMs = 3000) {
    const queued = this.queue.shift()

    if (queued !== undefined) return queued

    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('timed out waiting for frame')), timeoutMs)

      this.waiters.push(frame => {
        clearTimeout(timer)
        resolve(frame)
      })
    })
  }

  async waitClosed(timeoutMs = 3000) {
    if (this.closed) return

    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('socket did not close')), timeoutMs)

      this.ws.once('close', () => {
        clearTimeout(timer)
        resolve()
      })
    })
  }

  close() {
    try {
      this.ws.close()
    } catch {
      void 0
    }
  }
}

async function makeBridge(overrides = {}) {
  const dir = tmpDir()
  const fetchCalls = []
  const bridge = createMobileBridge({
    WebSocketImpl: WebSocketRouter,
    fetchImpl: async (url, options) => {
      fetchCalls.push({ options, url })

      return {
        arrayBuffer: async () => Buffer.from(JSON.stringify({ ok: true, url })),
        headers: { get: () => 'application/json' },
        status: 200
      }
    },
    getDashboard: async () => ({ baseUrl: 'http://127.0.0.1:59999', token: 'dash-token' }),
    hostName: 'Test Mac',
    jarvisHome: dir,
    lanPortPreference: 18776,
    log: () => {},
    ...overrides
  })

  await bridge.start()
  await bridge.setEnabled(true)

  return { bridge, dir, fetchCalls }
}

/** Tests dial loopback directly; payload.lan carries the real LAN addresses. */
function lanUrlFor(bridge) {
  return `ws://127.0.0.1:${bridge.getState().lanPort}/link`
}

async function createRelayPipeServer() {
  const server = http.createServer()
  const wss = new WebSocketServer({ noServer: true })
  const devices = new Map()
  let host = null
  let nextCid = 1

  const sendHostStatus = online => {
    for (const device of devices.values()) {
      if (device.readyState === WebSocket.OPEN) {
        device.send(JSON.stringify({ online, t: 'host_status' }))
      }
    }
  }

  server.on('upgrade', (req, socket, head) => {
    let pathname = ''

    try {
      pathname = new URL(req.url, 'http://relay.test').pathname
    } catch {
      socket.destroy()

      return
    }

    wss.handleUpgrade(req, socket, head, ws => {
      if (pathname.startsWith('/host/')) {
        host = ws

        ws.on('message', data => {
          let frame = null

          try {
            frame = JSON.parse(String(data))
          } catch {
            return
          }

          const device = devices.get(frame.cid)

          if (!device || device.readyState !== WebSocket.OPEN) return

          if (frame.t === 'msg' && typeof frame.d === 'string') {
            device.send(frame.d)
          } else if (frame.t === 'close') {
            device.close()
          }
        })

        ws.on('close', () => {
          if (host === ws) {
            host = null
            sendHostStatus(false)
          }
        })

        sendHostStatus(true)

        for (const cid of devices.keys()) {
          ws.send(JSON.stringify({ cid, t: 'open' }))
        }

        return
      }

      if (pathname.startsWith('/device/')) {
        const cid = `c${nextCid++}`

        devices.set(cid, ws)
        ws.send(JSON.stringify({ online: Boolean(host), t: 'host_status' }))

        if (host && host.readyState === WebSocket.OPEN) {
          host.send(JSON.stringify({ cid, t: 'open' }))
        }

        ws.on('message', data => {
          if (!host || host.readyState !== WebSocket.OPEN) {
            ws.send(JSON.stringify({ online: false, t: 'host_status' }))

            return
          }

          host.send(JSON.stringify({ cid, d: String(data), t: 'msg' }))
        })

        ws.on('close', () => {
          devices.delete(cid)

          if (host && host.readyState === WebSocket.OPEN) {
            host.send(JSON.stringify({ cid, t: 'close' }))
          }
        })

        return
      }

      ws.close()
    })
  })

  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))

  return {
    close: () =>
      new Promise(resolve => {
        wss.close(() => server.close(resolve))
      }),
    url: `http://127.0.0.1:${server.address().port}`
  }
}

async function pairPhone(bridge) {
  const pairing = bridge.createPairing()
  const payload = parsePairingUrl(pairing.url)
  const key = fromB64url(payload.key)
  const lanUrl = lanUrlFor(bridge)
  const phone = await new FakePhone(lanUrl, { key, keyId: `pair:${payload.pair}` }).open()

  phone.send('pair.request', { deviceModel: 'iPhone17,1', deviceName: 'Test iPhone', os: 'iOS 26' })

  const ok = await phone.next()

  assert.equal(ok.type, 'pair.ok')

  return { key, lanUrl, payload, phone, ...ok.body }
}

async function connectDevice(bridge, { deviceId, deviceToken, key, lanUrl }) {
  const phone = await new FakePhone(lanUrl, { key, keyId: `dev:${deviceId}` }).open()

  phone.send('hello', { deviceToken })

  const ok = await phone.next()

  assert.equal(ok.type, 'hello.ok')

  return phone
}

// ── Crypto ──────────────────────────────────────────────────────────────

test('envelope roundtrip preserves type, seq and body', () => {
  const key = generateLinkKey()
  const sealed = sealEnvelope(key, 'dev:abc', 7, 'rpc', { frame: { id: 1, method: 'prompt.submit' } })
  const opened = openEnvelope(key, sealed)

  assert.deepEqual(opened, {
    body: { frame: { id: 1, method: 'prompt.submit' } },
    keyId: 'dev:abc',
    seq: 7,
    type: 'rpc'
  })
})

test('envelopes reject tampering, wrong keys, and key-id swaps', () => {
  const key = generateLinkKey()
  const sealed = sealEnvelope(key, 'dev:abc', 1, 'ping', {})

  const flipped = JSON.parse(sealed)
  const bytes = fromB64url(flipped.c)

  bytes[0] ^= 0xff
  flipped.c = bytes.toString('base64url')
  assert.throws(() => openEnvelope(key, JSON.stringify(flipped)))

  assert.throws(() => openEnvelope(generateLinkKey(), sealed))

  // AAD binds the key id: relabeling dev:abc → dev:evil must fail to open.
  const relabeled = JSON.parse(sealed)

  relabeled.k = 'dev:evil'
  assert.throws(() => openEnvelope(key, JSON.stringify(relabeled)))
})

test('pairing url roundtrips through parse', () => {
  const key = generateLinkKey()
  const url = buildPairingUrl({
    expiresAt: 123456,
    hostId: 'host-id-abcdef123456',
    hostName: 'Test Mac',
    lanUrls: ['ws://192.168.1.20:8776/link'],
    linkKey: key,
    pairingId: 'pairing123',
    relayUrl: 'https://relay.example.workers.dev'
  })
  const parsed = parsePairingUrl(url)

  assert.equal(parsed.host, 'host-id-abcdef123456')
  assert.equal(parsed.pair, 'pairing123')
  assert.equal(parsed.relay, 'https://relay.example.workers.dev')
  assert.deepEqual(fromB64url(parsed.key), key)
  assert.equal(parsePairingUrl('jarvis-link://v2?d=zzz'), null)
})

test('interop vectors open with their embedded keys', () => {
  for (const vector of generateTestVectors()) {
    const opened = openEnvelope(fromB64url(vector.key), vector.envelope)

    assert.deepEqual(opened, { ...vector.expected, body: vector.expected.body })
  }
})

// ── Store ───────────────────────────────────────────────────────────────

test('store mints a stable host identity and manages devices', () => {
  const dir = tmpDir()
  const store = createMobileLinkStore({ dir })

  const identity = store.ensureIdentity()

  assert.ok(identity.hostId.length >= 16)
  assert.deepEqual(store.ensureIdentity().hostId, identity.hostId)

  const { device, token } = store.addDevice({ keyB64: 'a2V5', model: 'iPhone17,1', name: 'Phone' })

  assert.ok(store.verifyDeviceToken(device.id, token))
  assert.ok(!store.verifyDeviceToken(device.id, 'wrong'))

  assert.ok(store.revokeDevice(device.id))
  assert.ok(!store.verifyDeviceToken(device.id, token))
  assert.ok(!store.revokeDevice(device.id), 'second revoke is a no-op')

  // Reload from disk — everything persists.
  const reloaded = createMobileLinkStore({ dir })

  assert.equal(reloaded.listDevices().length, 1)
  assert.ok(reloaded.listDevices()[0].revokedAt)
})

// ── Bridge: pairing + auth ──────────────────────────────────────────────

test('QR pairing mints a device and hello authenticates it', async () => {
  const { bridge } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    assert.equal(paired.hostName, 'Test Mac')
    assert.ok(paired.deviceId)
    assert.ok(paired.deviceToken)

    const state = bridge.getState()

    assert.equal(state.devices.length, 1)
    assert.equal(state.devices[0].name, 'Test iPhone')

    // Promote the same connection to the device identity.
    paired.phone.seqOut = 0
    paired.phone.keyId = `dev:${paired.deviceId}`
    paired.phone.send('hello', { deviceToken: paired.deviceToken })

    const hello = await paired.phone.next()

    assert.equal(hello.type, 'hello.ok')
    assert.equal(hello.body.brain, 'ready')
    assert.ok(Array.isArray(hello.body.lan))

    paired.phone.close()
  } finally {
    bridge.stop()
  }
})

test('pairing codes are one-shot and unknown ones drop the socket', async () => {
  const { bridge } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    // Same pairing id again → pair.err used.
    const again = await new FakePhone(paired.lanUrl, {
      key: paired.key,
      keyId: `pair:${paired.payload.pair}`
    }).open()

    again.send('pair.request', { deviceName: 'Second' })

    const err = await again.next()

    assert.equal(err.type, 'pair.err')
    assert.equal(err.body.code, 'used')
    await again.waitClosed()

    // Unknown pairing id → closed without a reply.
    const unknown = await new FakePhone(paired.lanUrl, {
      key: paired.key,
      keyId: 'pair:doesnotexist'
    }).open()

    unknown.send('pair.request', { deviceName: 'Nope' })
    await unknown.waitClosed()
  } finally {
    bridge.stop()
  }
})

test('expired pairings are refused', async () => {
  let clock = 1_000_000
  const { bridge } = await makeBridge({ now: () => clock })

  try {
    const pairing = bridge.createPairing()
    const payload = parsePairingUrl(pairing.url)

    clock += 6 * 60_000

    const phone = await new FakePhone(lanUrlFor(bridge), {
      key: fromB64url(payload.key),
      keyId: `pair:${payload.pair}`
    }).open()

    phone.send('pair.request', { deviceName: 'Late' })

    const err = await phone.next()

    assert.equal(err.type, 'pair.err')
    assert.equal(err.body.code, 'expired')
    await phone.waitClosed()
  } finally {
    bridge.stop()
  }
})

test('hello with a bad token is refused; revocation kicks live sessions', async () => {
  const { bridge } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    const impostor = await new FakePhone(paired.lanUrl, {
      key: paired.key,
      keyId: `dev:${paired.deviceId}`
    }).open()

    impostor.send('hello', { deviceToken: 'stolen-key-no-token' })

    const err = await impostor.next()

    assert.equal(err.type, 'hello.err')
    assert.equal(err.body.code, 'unknown_device')
    await impostor.waitClosed()

    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    assert.equal((await phone.next()).type, 'upstream.status')

    bridge.revokeDevice(paired.deviceId)

    // The live session hears the revocation and is closed.
    const notice = await phone.next()

    assert.equal(notice.type, 'hello.err')
    assert.equal(notice.body.code, 'revoked')
    await phone.waitClosed()

    // Reconnecting after revocation is refused at hello.
    const back = await new FakePhone(paired.lanUrl, {
      key: paired.key,
      keyId: `dev:${paired.deviceId}`
    }).open()

    back.send('hello', { deviceToken: paired.deviceToken })

    const refused = await back.next()

    assert.equal(refused.type, 'hello.err')
    assert.equal(refused.body.code, 'revoked')
  } finally {
    bridge.stop()
  }
})

test('replayed sequence numbers are dropped without closing the session', async () => {
  const { bridge } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    await phone.next() // upstream.status ready

    phone.send('ping', { ts: 1 }, { rawSeq: 5 })
    assert.equal((await phone.next()).type, 'pong')

    // Replay seq 5 → silently dropped.
    phone.send('ping', { ts: 2 }, { rawSeq: 5 })
    phone.send('ping', { ts: 3 }, { rawSeq: 6 })

    const pong = await phone.next()

    assert.equal(pong.type, 'pong')
    assert.equal(pong.body.ts, 3, 'the replayed ping must not have produced a pong')

    phone.close()
  } finally {
    bridge.stop()
  }
})

// ── Bridge: proxying ────────────────────────────────────────────────────

test('allowed rpc methods flow to the upstream and responses flow back', async () => {
  fakeUpstreams.length = 0

  const { bridge } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })
    const status = await phone.next()

    assert.equal(status.type, 'upstream.status')
    assert.equal(status.body.state, 'ready')

    const upstream = fakeUpstreams.at(-1)

    phone.send('rpc', { frame: { id: 'r1', jsonrpc: '2.0', method: 'prompt.submit', params: { session_id: 's', text: 'hi' } } })

    await new Promise(resolve => setTimeout(resolve, 50))
    assert.equal(upstream.sent.length, 1)
    assert.equal(JSON.parse(upstream.sent[0]).method, 'prompt.submit')

    upstream.emit('message', JSON.stringify({ id: 'r1', jsonrpc: '2.0', result: { ok: true } }))

    const reply = await phone.next()

    assert.equal(reply.type, 'rpc')
    assert.deepEqual(reply.body.frame.result, { ok: true })

    upstream.emit('message', JSON.stringify({ jsonrpc: '2.0', method: 'event', params: { type: 'message.delta', payload: { text: 'hey' } } }))

    const event = await phone.next()

    assert.equal(event.body.frame.params.type, 'message.delta')

    phone.close()
  } finally {
    bridge.stop()
  }
})

test('disallowed rpc methods are refused before the upstream sees them', async () => {
  fakeUpstreams.length = 0

  const { bridge } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    await phone.next() // upstream.status

    const upstream = fakeUpstreams.at(-1)

    phone.send('rpc', { frame: { id: 'x1', jsonrpc: '2.0', method: 'shell.exec', params: { command: 'rm -rf /' } } })

    const refusal = await phone.next()

    assert.equal(refusal.type, 'rpc')
    assert.equal(refusal.body.frame.id, 'x1')
    assert.equal(refusal.body.frame.error.code, -32601)
    assert.equal(upstream.sent.length, 0, 'refused methods must never reach the dashboard')

    phone.close()
  } finally {
    bridge.stop()
  }
})

test('mobile config rpc is limited to reasoning effort', () => {
  assert.equal(isRpcAllowedFromMobile({
    id: 'r1',
    jsonrpc: '2.0',
    method: 'config.get',
    params: { key: 'reasoning' }
  }), true)
  assert.equal(isRpcAllowedFromMobile({
    id: 'r2',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'reasoning', value: 'high' }
  }), true)
  assert.equal(isRpcAllowedFromMobile({
    id: 'r3',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'reasoning', value: 'none' }
  }), true)
  assert.equal(isRpcAllowedFromMobile({
    id: 'r4',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'fast', value: 'fast' }
  }), false)
  assert.equal(isRpcAllowedFromMobile({
    id: 'r5',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'reasoning', value: 'show' }
  }), false)
  assert.equal(isRpcAllowedFromMobile({
    id: 'r6',
    jsonrpc: '2.0',
    method: 'config.get',
    params: { key: 'full' }
  }), false)
})

test('mobile config.set model accepts real model strings and nothing else', () => {
  assert.equal(isRpcAllowedFromMobile({
    id: 'm1',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', session_id: 's1', value: 'claude-sonnet-5 --provider anthropic' }
  }), true)
  assert.equal(isRpcAllowedFromMobile({
    id: 'm2',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', value: 'openrouter/anthropic/claude-3.5-sonnet --provider openrouter' }
  }), true)
  assert.equal(isRpcAllowedFromMobile({
    id: 'm3',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', value: 'gpt-4o' }
  }), true)
  // Anything beyond "<model> --provider <prov>" — extra flags, spaces,
  // shell-ish characters — must be refused.
  assert.equal(isRpcAllowedFromMobile({
    id: 'm4',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', value: 'gpt-4o --provider openai --danger' }
  }), false)
  assert.equal(isRpcAllowedFromMobile({
    id: 'm5',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', value: 'model; rm -rf ~' }
  }), false)
  assert.equal(isRpcAllowedFromMobile({
    id: 'm6',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', value: '' }
  }), false)
  assert.equal(isRpcAllowedFromMobile({
    id: 'm7',
    jsonrpc: '2.0',
    method: 'config.set',
    params: { key: 'model', value: `${'a'.repeat(300)}` }
  }), false)
})

test('http proxy honors the allowlist and forwards the dashboard token', async () => {
  const { bridge, fetchCalls } = await makeBridge()

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    await phone.next() // upstream.status

    phone.send('http', {
      body: Buffer.from(JSON.stringify({ text: 'hello' })).toString('base64url'),
      contentType: 'application/json',
      id: 'h1',
      method: 'POST',
      path: '/api/audio/speak'
    })

    const ok = await phone.next()

    assert.equal(ok.type, 'http.res')
    assert.equal(ok.body.id, 'h1')
    assert.equal(ok.body.status, 200)
    assert.equal(fetchCalls.length, 1)
    assert.equal(fetchCalls[0].url, 'http://127.0.0.1:59999/api/audio/speak')
    assert.equal(fetchCalls[0].options.headers.authorization, 'Bearer dash-token')

    phone.send('http', { id: 'h2', method: 'GET', path: '/api/env' })

    const refused = await phone.next()

    assert.equal(refused.body.status, 403)
    assert.equal(fetchCalls.length, 1, 'refused paths must not be fetched')

    // Query strings ride along on allowed paths.
    phone.send('http', { id: 'h3', method: 'GET', path: '/api/sessions?limit=20' })

    const sessions = await phone.next()

    assert.equal(sessions.body.status, 200)
    assert.ok(fetchCalls[1].url.endsWith('/api/sessions?limit=20'))

    // Parameterized transcript reads are allowed; other nested paths aren't.
    phone.send('http', { id: 'h4', method: 'GET', path: '/api/sessions/abc123/messages' })

    const transcript = await phone.next()

    assert.equal(transcript.body.status, 200)

    // Session mutations (delete / rename / archive) are proxied…
    phone.send('http', { id: 'h5', method: 'DELETE', path: '/api/sessions/abc123' })

    const deleted = await phone.next()

    assert.equal(deleted.body.status, 200)

    phone.send('http', { id: 'h6', method: 'PATCH', path: '/api/sessions/abc123' })

    const patched = await phone.next()

    assert.equal(patched.body.status, 200)

    // …but mutations outside the session family stay refused.
    phone.send('http', { id: 'h7', method: 'DELETE', path: '/api/files' })

    const denied = await phone.next()

    assert.equal(denied.body.status, 403)

    phone.close()
  } finally {
    bridge.stop()
  }
})

test('large http responses are chunked for relay-safe delivery', async () => {
  const largeBody = Buffer.from(JSON.stringify({
    models: Array.from({ length: 12000 }, (_, index) => `model-${index}`)
  }))
  const { bridge } = await makeBridge({
    fetchImpl: async () => ({
      arrayBuffer: async () => largeBody,
      headers: { get: () => 'application/json' },
      status: 200
    })
  })

  try {
    const paired = await pairPhone(bridge)

    paired.phone.close()

    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    await phone.next() // upstream.status

    phone.send('http', { id: 'big1', method: 'GET', path: '/api/model/options' })

    const chunks = []
    let total = null

    do {
      const frame = await phone.next()

      chunks.push(frame)
      assert.equal(frame.type, 'http.chunk')
      assert.equal(frame.body.id, 'big1')
      assert.equal(frame.body.status, 200)
      assert.equal(frame.body.contentType, 'application/json')
      total = frame.body.total
    } while (chunks.length < total)

    assert.equal(total, chunks.length)
    assert.equal(chunks.map(chunk => chunk.body.index).join(','), Array.from({ length: total }, (_, index) => index).join(','))
    assert.equal(Buffer.from(chunks.map(chunk => chunk.body.body).join(''), 'base64url').toString('utf8'), largeBody.toString('utf8'))

    phone.close()
  } finally {
    bridge.stop()
  }
})

// ── Relay uplink ────────────────────────────────────────────────────────

test('bridge dials the relay, pipes envelopes by cid, and closes on revoke', async () => {
  const relayConnections = []
  const relayServer = new WebSocketServer({ host: '127.0.0.1', port: 0 })

  relayServer.on('connection', (socket, request) => {
    relayConnections.push({ request, socket })
  })

  await new Promise(resolve => relayServer.once('listening', resolve))

  const relayPort = relayServer.address().port
  const { bridge } = await makeBridge()

  try {
    bridge.setRelayUrl(`http://127.0.0.1:${relayPort}`)

    // The bridge dials out with its host key.
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('bridge never dialed the relay')), 3000)
      const poll = setInterval(() => {
        if (relayConnections.length > 0) {
          clearTimeout(timer)
          clearInterval(poll)
          resolve()
        }
      }, 20)
    })

    const { request, socket } = relayConnections[0]

    assert.match(request.url, /^\/host\/[A-Za-z0-9_-]{16,}$/)
    assert.ok(request.headers['x-jarvis-host-key'])

    const state = bridge.getState()

    assert.equal(state.hostId, request.url.split('/').at(-1))

    // Pair a phone "through the relay": DO-style frames over this socket.
    const pairing = bridge.createPairing()
    const payload = parsePairingUrl(pairing.url)
    const key = fromB64url(payload.key)

    const fromBridge = []
    const waiters = []

    socket.on('message', data => {
      const frame = JSON.parse(String(data))
      const waiter = waiters.shift()

      if (waiter) waiter(frame)
      else fromBridge.push(frame)
    })

    const nextFromBridge = () =>
      fromBridge.shift() ??
      new Promise((resolve, reject) => {
        const timer = setTimeout(() => reject(new Error('no frame from bridge')), 3000)

        waiters.push(frame => {
          clearTimeout(timer)
          resolve(frame)
        })
      })

    socket.send(JSON.stringify({ cid: 'c1', t: 'open' }))
    socket.send(JSON.stringify({ cid: 'c1', d: sealEnvelope(key, `pair:${payload.pair}`, 1, 'pair.request', { deviceName: 'Relay iPhone' }), t: 'msg' }))

    const reply = await nextFromBridge()

    assert.equal(reply.t, 'msg')
    assert.equal(reply.cid, 'c1')

    const opened = openEnvelope(key, reply.d)

    assert.equal(opened.type, 'pair.ok')

    // hello over the relay path with the minted identity
    socket.send(
      JSON.stringify({
        cid: 'c1',
        d: sealEnvelope(key, `dev:${opened.body.deviceId}`, 1, 'hello', { deviceToken: opened.body.deviceToken }),
        t: 'msg'
      })
    )

    const helloReply = await nextFromBridge()

    assert.equal(openEnvelope(key, helloReply.d).type, 'hello.ok')

    // Revoking the device force-closes its relay connection.
    bridge.revokeDevice(opened.body.deviceId)

    const frames = [await nextFromBridge(), await nextFromBridge(), await nextFromBridge()]
    const kinds = frames.map(frame => frame.t)

    assert.ok(kinds.includes('close'), `expected a close frame, got ${JSON.stringify(kinds)}`)
  } finally {
    bridge.stop()
    relayServer.close()
  }
})

test('relay self-test round-trips through the relay into the local bridge without adding a device', async () => {
  const relay = await createRelayPipeServer()
  const { bridge } = await makeBridge()

  try {
    bridge.setRelayUrl(relay.url)

    const result = await bridge.testRelay()

    assert.equal(result.ok, true, result.error)
    assert.equal(result.relayUrl, relay.url)
    assert.ok(result.durationMs >= 0)
    assert.equal(bridge.getState().devices.length, 0)
  } finally {
    bridge.stop()
    await relay.close()
  }
})

test('relay self-test reports a missing configured relay', async () => {
  const { bridge } = await makeBridge()

  try {
    const result = await bridge.testRelay()

    assert.equal(result.ok, false)
    assert.equal(result.code, 'missing-relay')
    assert.match(result.error, /No relay URL/)
  } finally {
    bridge.stop()
  }
})

test('relay watchdog recycles an unresponsive uplink and reconnects', async () => {
  // autoPong:false makes the server swallow protocol pings — the same
  // symptom as a half-open uplink (NAT drop, Cloudflare idle-kill, Mac
  // sleep). Before the watchdog existed this left the bridge claiming
  // "relay: connected" forever while phones could never reach the host.
  const relayConnections = []
  const relayServer = new WebSocketServer({ autoPong: false, host: '127.0.0.1', port: 0 })

  relayServer.on('connection', socket => {
    relayConnections.push(socket)
  })

  await new Promise(resolve => relayServer.once('listening', resolve))

  const waitFor = (predicate, what, timeoutMs = 6000) =>
    new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        clearInterval(poll)
        reject(new Error(`timed out waiting for ${what}`))
      }, timeoutMs)
      const poll = setInterval(() => {
        if (predicate()) {
          clearTimeout(timer)
          clearInterval(poll)
          resolve()
        }
      }, 20)
    })

  const relayPort = relayServer.address().port
  const { bridge } = await makeBridge({ relayLivenessGraceMs: 250, relayPingIntervalMs: 100 })

  try {
    bridge.setRelayUrl(`http://127.0.0.1:${relayPort}`)

    await waitFor(() => relayConnections.length >= 1, 'first uplink')

    // No pongs ever arrive, so the liveness watchdog must terminate the
    // zombie and the bridge must dial a fresh uplink by itself.
    await waitFor(() => relayConnections.length >= 2, 'watchdog-driven reconnect')

    assert.ok(relayConnections[0].readyState >= 2, 'first uplink should be closing/closed after the recycle')
  } finally {
    bridge.stop()
    relayServer.close()
  }
})

// ── Helpers ────────────────────────────────────────────────────────────

test('relayHostEndpoint normalizes schemes', () => {
  assert.equal(relayHostEndpoint('https://x.workers.dev', 'abc'), 'wss://x.workers.dev/host/abc')
  assert.equal(relayHostEndpoint('http://127.0.0.1:1234/', 'abc'), 'ws://127.0.0.1:1234/host/abc')
  assert.equal(relayHostEndpoint('x.workers.dev', 'abc'), 'wss://x.workers.dev/host/abc')
  assert.equal(relayHostEndpoint('', 'abc'), null)
  assert.equal(relayDeviceEndpoint('https://x.workers.dev', 'abc'), 'wss://x.workers.dev/device/abc')
  assert.equal(relayDeviceEndpoint('http://127.0.0.1:1234/', 'abc'), 'ws://127.0.0.1:1234/device/abc')
  assert.equal(relayDeviceEndpoint('x.workers.dev', 'abc'), 'wss://x.workers.dev/device/abc')
  assert.equal(relayDeviceEndpoint('', 'abc'), null)
})

test('collectLanUrls includes the mDNS name and only IPv4 externals', () => {
  const urls = collectLanUrls(8776)

  assert.ok(urls.every(url => url.startsWith('ws://') && url.endsWith(':8776/link')))
  assert.equal(collectLanUrls(null).length, 0)
})

// ── Agent sessions (Claude Code / Codex) RPCs ──────────────────────────

function makeFakeAgents() {
  const watches = []
  const sendCalls = []
  const steerCalls = []
  const configureCalls = []
  const commandCalls = []
  let runCallback = null

  return {
    commandCalls,
    configureCalls,
    configure: async (provider, params) => {
      configureCalls.push({ provider, ...params })

      return { applied: params, deferred: false }
    },
    dispose: () => {},
    emitRun(event) {
      runCallback?.(event)
    },
    listSessions: provider => [{ cwd: '/tmp', id: 's1', provider, running: false, title: 'Fix bug', updated_at: 123 }],
    onRunEvent(callback) {
      runCallback = callback

      return () => {
        runCallback = null
      }
    },
    providers: () => [{ available: true, id: 'claude', label: 'Claude Code' }],
    runCommand: async (provider, params) => {
      commandCalls.push({ provider, ...params })

      return { ok: true }
    },
    readMessages: (provider, sessionId) => ({
      cwd: '/tmp',
      messages: [{ id: 'm1', role: 'user', text: `hello ${provider}/${sessionId}`, thinking: '', tools: [], ts: 1 }],
      model: 'claude-fable-5',
      running: false,
      sending: false,
      total: 1
    }),
    runningRuns: () => [],
    sendCalls,
    sendPrompt: async (provider, params) => {
      sendCalls.push({ provider, ...params })

      return { run_id: 'run-1', session_id: params.sessionId || 'fresh-id' }
    },
    steer: async (provider, params) => {
      steerCalls.push({ provider, ...params })

      return { ok: true }
    },
    steerCalls,
    stop: async () => ({ ok: true }),
    watch(provider, sessionId, callback) {
      const entry = { callback, provider, sessionId, stopped: false }

      watches.push(entry)

      return () => {
        entry.stopped = true
      }
    },
    watches
  }
}

test('agent.* rpcs are answered locally without touching the upstream', async () => {
  const fakeAgents = makeFakeAgents()
  const { bridge } = await makeBridge({ agentSessionsImpl: fakeAgents })

  try {
    const paired = await pairPhone(bridge)
    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    // No upstream socket exists in this test setup — local answers only.
    phone.send('rpc', { frame: { id: 1, jsonrpc: '2.0', method: 'agent.sessions', params: { provider: 'claude' } } })

    let reply = await phone.next()

    while (reply && reply.type !== 'rpc') reply = await phone.next()

    assert.equal(reply.body.frame.id, 1)
    assert.equal(reply.body.frame.result.sessions[0].title, 'Fix bug')

    phone.send('rpc', { frame: { id: 2, jsonrpc: '2.0', method: 'agent.messages', params: { provider: 'codex', session_id: 's1' } } })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(reply.body.frame.result.messages[0].text, 'hello codex/s1')

    // Unknown provider is refused with a param error.
    phone.send('rpc', { frame: { id: 3, jsonrpc: '2.0', method: 'agent.sessions', params: { provider: 'gemini' } } })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.ok(reply.body.frame.error)
    assert.match(reply.body.frame.error.message, /unknown agent provider/)

    // Sending returns the run ack.
    phone.send('rpc', { frame: { id: 4, jsonrpc: '2.0', method: 'agent.send', params: { provider: 'claude', session_id: 's1', text: 'go' } } })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(reply.body.frame.result.run_id, 'run-1')
    assert.equal(fakeAgents.sendCalls[0].planMode, undefined)

    // Provider-native quick commands stay local too.
    phone.send('rpc', { frame: { id: 41, jsonrpc: '2.0', method: 'agent.command', params: { command: 'compact', provider: 'codex', session_id: 's1' } } })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.deepEqual(reply.body.frame.result, { ok: true })
    assert.equal(fakeAgents.commandCalls[0].command, 'compact')
    assert.equal(fakeAgents.commandCalls[0].sessionId, 's1')

    // Watch → transcript change pushes an event frame.
    phone.send('rpc', { frame: { id: 5, jsonrpc: '2.0', method: 'agent.watch', params: { provider: 'claude', session_id: 's1' } } })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(reply.body.frame.result.ok, true)
    assert.equal(fakeAgents.watches.length, 1)

    fakeAgents.watches[0].callback({ provider: 'claude', session_id: 's1' })
    reply = await phone.next()
    while (reply && !(reply.type === 'rpc' && reply.body.frame.method === 'event')) reply = await phone.next()
    assert.equal(reply.body.frame.params.type, 'agent.update')
    assert.equal(reply.body.frame.params.payload.session_id, 's1')

    // Run lifecycle events broadcast to authed phones.
    fakeAgents.emitRun({ ok: true, provider: 'claude', run_id: 'run-1', session_id: 's1', type: 'agent.run_done' })
    reply = await phone.next()
    while (reply && !(reply.type === 'rpc' && reply.body.frame.method === 'event')) reply = await phone.next()
    assert.equal(reply.body.frame.params.type, 'agent.run_done')

    // Unwatch stops the watcher.
    phone.send('rpc', { frame: { id: 6, jsonrpc: '2.0', method: 'agent.unwatch', params: { provider: 'claude', session_id: 's1' } } })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(fakeAgents.watches[0].stopped, true)

    phone.close()
  } finally {
    bridge.stop()
  }
})

test('agent.send passes a well-formed model through and strips garbage', async () => {
  const fakeAgents = makeFakeAgents()
  const { bridge } = await makeBridge({ agentSessionsImpl: fakeAgents })

  try {
    const paired = await pairPhone(bridge)
    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    phone.send('rpc', {
      frame: { id: 1, jsonrpc: '2.0', method: 'agent.send', params: { model: 'claude-opus-4-8', provider: 'claude', session_id: 's1', text: 'go' } }
    })

    let reply = await phone.next()

    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(fakeAgents.sendCalls[0].model, 'claude-opus-4-8')

    // A garbage/injection-shaped value is dropped rather than forwarded.
    phone.send('rpc', {
      frame: { id: 2, jsonrpc: '2.0', method: 'agent.send', params: { model: 'not a model; rm -rf', provider: 'claude', session_id: 's1', text: 'go' } }
    })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(fakeAgents.sendCalls[1].model, undefined)

    phone.close()
  } finally {
    bridge.stop()
  }
})

test('agent.send forwards effort/planMode and routes steer:true to agents.steer instead of sendPrompt', async () => {
  const fakeAgents = makeFakeAgents()
  const { bridge } = await makeBridge({ agentSessionsImpl: fakeAgents })

  try {
    const paired = await pairPhone(bridge)
    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    phone.send('rpc', {
      frame: { id: 1, jsonrpc: '2.0', method: 'agent.send', params: { effort: 'high', planMode: true, provider: 'codex', session_id: 's1', text: 'go' } }
    })

    let reply = await phone.next()

    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.equal(fakeAgents.sendCalls[0].effort, 'high')
    assert.equal(fakeAgents.sendCalls[0].planMode, true)
    assert.equal(fakeAgents.steerCalls.length, 0)

    phone.send('rpc', {
      frame: { id: 2, jsonrpc: '2.0', method: 'agent.send', params: { provider: 'codex', session_id: 's1', steer: true, text: 'redirect' } }
    })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()

    assert.equal(fakeAgents.steerCalls.length, 1)
    assert.equal(fakeAgents.steerCalls[0].text, 'redirect')
    assert.equal(fakeAgents.sendCalls.length, 1, 'steer:true must not also call sendPrompt')
    assert.deepEqual(reply.body.frame.result, { ok: true })

    phone.close()
  } finally {
    bridge.stop()
  }
})

test('agent.configure requires session_id and forwards validated model/effort/planMode', async () => {
  const fakeAgents = makeFakeAgents()
  const { bridge } = await makeBridge({ agentSessionsImpl: fakeAgents })

  try {
    const paired = await pairPhone(bridge)
    const phone = await connectDevice(bridge, { ...paired, lanUrl: paired.lanUrl })

    phone.send('rpc', { frame: { id: 1, jsonrpc: '2.0', method: 'agent.configure', params: { provider: 'claude', text: 'no session id' } } })

    let reply = await phone.next()

    while (reply && reply.type !== 'rpc') reply = await phone.next()
    assert.ok(reply.body.frame.error)
    assert.match(reply.body.frame.error.message, /session_id/)

    phone.send('rpc', {
      frame: { id: 2, jsonrpc: '2.0', method: 'agent.configure', params: { model: 'claude-sonnet-5', planMode: true, provider: 'claude', session_id: 's1' } }
    })
    reply = await phone.next()
    while (reply && reply.type !== 'rpc') reply = await phone.next()

    assert.equal(fakeAgents.configureCalls[0].sessionId, 's1')
    assert.equal(fakeAgents.configureCalls[0].model, 'claude-sonnet-5')
    assert.equal(fakeAgents.configureCalls[0].planMode, true)
    // effort wasn't sent by the phone at all — must stay undefined, not
    // coerced to null (null would mean "explicitly reset it").
    assert.equal('effort' in fakeAgents.configureCalls[0], true)
    assert.equal(fakeAgents.configureCalls[0].effort, undefined)

    phone.close()
  } finally {
    bridge.stop()
  }
})
